routes/web.php
<?php

use App\Product;
use App\User;
use App\Order;
use App\Wallet;
use App\Frontslide;

/*
|----------------------------- ---------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/getCity', 'FrontController@getCity')->name('rajaOngkir.getCity');
Route::get('/getSubdistrict', 'FrontController@getSubdistrict')->name('rajaOngkir.getSubdistrict');
Route::get('/getCost', 'FrontController@getCost')->name('rajaOngkir.getCost');

Route::prefix('/member')->group(function (){
  Route::resource('/', 'MemberController');
    Route::get('/home', 'MemberController@index');
    Route::get('/catalog', 'MemberController@catalog');
    Route::get('/product', 'MemberController@product');

    Route::get('/productdetail/{id}', 'MemberController@productdetail');
    Route::get('/productdetail/{id}/productasset', 'MemberController@productasset');
    Route::get('/detailproduct/{id}', 'MemberController@detailproduct');
    Route::get('/setting', 'MemberController@setting');
    Route::get('/setting/profile', 'MemberController@profile');
    Route::get('/setting/password', 'MemberController@password');
    Route::get('/setting/bank', 'MemberController@bank');
    Route::get('/setting/profiletoko', 'MemberController@profiletoko');
    Route::get('/setting/logo', 'MemberController@logo');

    Route::get('/setting/frontslide', 'MemberController@frontslide');

    Route::post('/setting/frontslidepost', 'MemberController@frontslidepost');
    Route::get('/setting/frontslidel/{id}', function($id){
      $data = Frontslide::findOrFail($id);
      File::delete('images/slides/' . @$data->picture);
      $data->delete();
      return redirect()->back()->with('success','B erhasil Delete Data');
      });

    Route::post('/setting/logoupdate', 'MemberController@logoupdate')->name('logoupdate');

    Route::get('/team', 'MemberController@team');

    Route::get('/teamadd', 'MemberController@teamadd');

    Route::get('/gajian', 'MemberController@gajian');
    Route::get('/gajianout', 'MemberController@gajianout');

    Route::get('/request', 'MemberController@request');

    Route::get('/coupon', 'MemberController@coupon');
    Route::get('/order', 'MemberController@order');
    Route::get('/landingpage', 'MemberController@landingpage');
    Route::get('/apps', 'MemberController@apps');

    Route::prefix('/order')->group(function (){
      Route::resource('/', 'MemberOrderController');
        Route::get('/prospek', 'MemberOrderController@prospek');
        Route::get('/catalog', 'MemberOrderController@catalog');
        Route::get('/detail/{id}', 'MemberOrderController@detail');


       });
   });
Route::prefix('/admin')->group(function (){
  Route::resource('/', 'AdminController');
    Route::get('/home', 'MemberController@index');
    Route::get('/catalog', 'MemberController@catalog');
    Route::get('/product', 'MemberController@product');

    Route::get('/productdetail/{id}', 'MemberController@productdetail');

    Route::get('/detailproduct/{id}', 'MemberController@detailproduct');
    Route::get('/setting', 'MemberController@setting');
    Route::get('/team', 'MemberController@team');

    Route::get('/teamadd', 'MemberController@teamadd');

    Route::get('/gajian', 'MemberController@gajian');
    Route::get('/coupon', 'MemberController@coupon');
    Route::get('/order', 'MemberController@order');
    Route::get('/landingpage', 'MemberController@landingpage');
    Route::get('/apps', 'MemberController@apps');

    Route::prefix('/order')->group(function (){
      Route::resource('/', 'AdminOrderController');
        Route::get('/prospek', 'AdminOrderController@prospek');
        Route::get('/catalog', 'AdminOrderController@catalog');
        Route::get('/detail/{id}', 'AdminOrderController@catalog');


       });
   });


Route::prefix('/')->group(function (){
   Route::resource('/','FrontController');
   Route::get('/productdetail/{id}', 'FrontController@productdetail');
   Route::get('/front/category/{id}', 'FrontController@productcategory');

   /*
   Route::prefix('product')->group(function (){
            Route::resource('/','AdminProductController');
        });
        */
   });

Route::prefix('/test')->group(function (){
   Route::resource('/','TestController');
   Route::get('/create', 'TestController@create');
   });

Route::get('/admin', function () {
    return view('auth.login');
});


Route::get('/home', 'HomeController@index')->name('home');
Route::get('/wallet/reseller/{id}', 'WalletController@resellerWallet')->name('wallet.reseller');
Route::get('/wallet/admin', 'WalletController@adminWallet')->name('wallet.admin');
Route::get('/wallet/history', 'WalletController@historyWallet')->name('wallet.history');
Route::post('/wallet/update-status/{id}', 'WalletController@statusWallet')->name('wallet.status');
Route::get('/order/prospect', 'OrderController@prospect')->name('order.prospect');
Route::get('/order/confirm', 'OrderController@confirm')->name('order.confirm');
Route::get('/order/packing', 'OrderController@packing')->name('order.packing');
Route::get('/order/delivering', 'OrderController@delivering')->name('order.delivering');
Route::get('/order/success', 'OrderController@success')->name('order.success');
Route::get('/order/tracking', 'OrderController@tracking')->name('order.tracking');

Route::get('/order/detail/{id}', 'OrderController@detail')->name('order.detail');

Route::post('/order/track', 'OrderController@trackOrder')->name('order.trackOrder');
Route::get('/orders','OrderController@index')->name('order.sell');
Route::get('/product/destroy/{id}','ProductController@destroy');
Route::get('/reseller/destroy/{id}','ResellerController@destroy');

Route::resource('/product', 'ProductController');

Route::resource('/reseller', 'ResellerController');
Route::resource('/wallet', 'WalletController');
Route::resource('/resellerPackage', 'ResellerPackageController');
Route::resource('/order', 'OrderController');
Route::resource('/category', 'CategoryController');
Route::resource('/catalog', 'CatalogController');
Route::resource('/coupon', 'CouponController');
Route::resource('/resellerDashboard', 'ResellerDashboardController');
Route::resource('/user', 'UserController');
Route::resource('/bank', 'BankAccountController');
Route::resource('/asset', 'AssetController');
Route::resource('/stock', 'StockController');


Route::get('/disable-product/{id}', function($id){
  $product = Product::findOrFail($id);
  $product->status = 'inactive';
  $product->save();
  return redirect()->back();
});

Route::get('/enable-product/{id}', function($id){
  $product = Product::findOrFail($id);
  $product->status = 'active';
  $product->save();
  return redirect()->back();
});

Route::get('/disable-user/{id}', function($id){
  $user = User::findOrFail($id);
  $user->status = 'inactive';
  $user->save();
  return redirect()->back();
});

Route::get('/enable-user/{id}', function($id){
  $user = User::findOrFail($id);
  $user->status = 'active';
  $user->save();
  return redirect()->back();
});

Route::get('/prospect/{id}', function($id){
  $order = Order::findOrFail($id);
  $user->order_status = 'prospect';
  $order->save();
  return redirect()->save();
});

Route::get('/pending/{id}', function($id){
  $order = Order::findOrFail($id);
  $order->order_status = 'pending';
  $order->save();
  return redirect()->back();
});

Route::get('/konfirmasi/{id}', function($id){
  $order = Order::findOrFail($id);
  $order->order_status = 'processing';
  $order->save();
  // dd($order);

  return redirect()->back();
});

Route::get('/pembayaranDiterima/{id}', function($id){
  $order = Order::findOrFail($id);
  $order->order_status = 'paid';
  $order->save();
  return redirect()->back();
});

Route::get('/packing/{id}', function($id){
  $order = Order::findOrfail($id);
  $order->order_status = 'packing';
  $order->save();
  return redirect()->back();
});

Route::get('/pengiriman/{id}', function($id){
  $order = Order::findOrFail($id);
  $order->order_status = 'delivering';
  $order->save();
  return redirect()->back();
});

Route::get('/diTerima/{id}', function($id){

  $order = Order::findOrFail($id);
  $order->order_status = 'success';
  $order->save();

  $orderdetail = \DB::table('order_details')->where('order_id',$id)->sum('profit');
  $wallet = New Wallet();
  $wallet->user_id = $order->reseller_id;
  $wallet->balanced = $orderdetail;
  $wallet->type = 'Credit';
  $wallet->desc = "Profit Dari Penjualan Barang";
  $wallet->order_id = @$order->id;
  $wallet->save();

  return redirect()->back();

});

app/Reseller.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Reseller extends Model
{
    //
}

app/Http/Controllers/ResellerController.php
<?php

namespace App\Http\Controllers;

use App\Reseller;
use App\ResellerPackage;
use App\Shop;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class ResellerController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $resellers = User::select('users.*', 'reseller_packages.title as reseller_type_name')
            ->leftJoin('reseller_packages', 'reseller_packages.id', '=', 'users.reseller_type')
            ->where('user_type', 'reseller')
            ->get();
        return view('resellers.index', compact('resellers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $packages = ResellerPackage::all();

        return view('resellers.create', compact('packages'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'          => 'required',
            'email'         => 'required',
            'password'      => 'required|min:4|confirmed',
            'reseller_type' => 'required',
        ]);

        $request->merge([
            'password'  => Hash::make($request->password),
            'user_type' => 'reseller',
            'status'    => 'active'
        ]);

        $user = User::create($request->all());
        Shop::create([
            'user_id'       => $user->id,
            'domain'        => $request->domain,
            'company_name'  => $request->company_name,
            'email'         => $request->email,
            'phone'         => $request->phone,
            'no_rekening'   => $request->no_rekening,
            'nama_pemilik'  => $request->nama_pemilik,
            'nama_bank'     => $request->nama_bank,
        ]);

        return redirect()->route('reseller.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // $data = Reseller::findOrFail($id);
        // $data = User::findOrFail($id);
        $data = Shop::where('user_id', '=', $id)->first();
        $packages = ResellerPackage::all();
        if($data == null || $packages == null)
          return "Data Kosong";
        else
          return view('resellers.edit', compact('data', 'packages'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // $resellers = Reseller::findOrFail($id);
        $users = User::where('id', '=', $id)->firstOrFail();
        $resellers = Shop::where('user_id', '=', $id)->firstOrFail();

        // $this->validate($request, [
        //     'email' => 'required',
        //     'reseller_type' => 'required',
        // ]);

        if ($request->password) {
            $this->validate($request, [
                'password' => 'required|min:8|confirmed',
            ]);

            $request->merge([
                'password' => Hash::make($request->password),
            ]);
        }

        $input = $request->all();
        $resellers->fill($input)->save();
        $users->reseller_type = $request->reseller_package_id;
        $users->save();

        return redirect()->back();
        // return redirect()->route('reseller.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // $reseller = Reseller::find($id);
        $reseller = User::where('id', '=', $id)->firstOrFail();
        $reseller->delete();
        return redirect()->route('reseller.index');
    }
}

resources/views/resellers/create.blade.php
@extends('layouts.default')

@section('content')
    <div class="single-product-tab-area mg-tb-15">
        <!-- Single pro tab review Start-->
        <div class="single-pro-review-area">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="review-tab-pro-inner">
                            <ul id="myTab3" class="tab-review-design">
                                <li class="active"><a href="#description"><i class="fa fa-pencil" aria-hidden="true"></i> Add New Reseller</a></li>
                            </ul>
                            <div id="myTabContent" class="tab-content custom-product-edit">
                                <div class="product-tab-list tab-pane fade active in" id="description">

                                    <form method="POST" action="{{ route('reseller.store') }}">
                                        @csrf
                                        <div class="row">
                                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                <div class="review-content-section">
                                                    <div class="input-group mg-b-pro-edt">
                                                        <span class="input-group-addon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
                                                        <input type="text" name="name" class="form-control" placeholder="Nama" required>
                                                    </div>
                                                    <div class="input-group mg-b-pro-edt">
                                                        <span class="input-group-addon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
                                                        <input type="email" name="email" class="form-control" placeholder="Email">
                                                    </div>
                                                    <div class="input-group mg-b-pro-edt">
                                                        <span class="input-group-addon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
                                                        <input type="text" name="phone" class="form-control" placeholder="Phone">
                                                    </div>
                                                    <div class="input-group mg-b-pro-edt">
                                                        <span class="input-group-addon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
                                                        <input type="text" name="domain" class="form-control" placeholder="Domain">
                                                    </div>
                                                    <div class="input-group mg-b-pro-edt">
                                                        <span class="input-group-addon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
                                                        <input type="text" name="company_name" class="form-control" placeholder="Nama Toko">
                                                    </div>
                                                    <div class="">
                                                        <label>Paket Reseller</label>
                                                        <select name="reseller_type" class="form-control pro-edt-select form-control-primary">
                                                            @foreach($packages as $key => $package)
                                                                <option value="{{ $package->id }}">{{ $package->title }}</option>
                                                            @endforeach
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                <div class="review-content-section">
                                                    <div class="input-group mg-b-pro-edt">
                                                        <span class="input-group-addon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
                                                        <input type="text" name="no_rekening" class="form-control" placeholder="No Rekening" required>
                                                    </div>
                                                    <div class="input-group mg-b-pro-edt">
                                                        <span class="input-group-addon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
                                                        <input type="text" name="nama_pemilik" class="form-control" placeholder="Nama Pemilik">
                                                    </div>
                                                    <div class="input-group mg-b-pro-edt">
                                                        <span class="input-group-addon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
                                                        <input type="text" name="nama_bank" class="form-control" placeholder="Nama Bank" required>
                                                    </div>
                                                    <div class="input-group mg-b-pro-edt">
                                                        <span class="input-group-addon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
                                                        <input type="password" name="password" class="form-control" placeholder="Password" required>
                                                    </div>
                                                    <div class="input-group mg-b-pro-edt">
                                                        <span class="input-group-addon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
                                                        <input type="password" name="password_confirmation" class="form-control" placeholder="Password Confirmation">
                                                    </div>
                                                </div>
                                            </div>
                                        </div><br><br>
                                        @if (Auth::user()->user_type != 'finance')
                                          <div class="row">
                                              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                  <div class="text-center mg-b-pro-edt custom-pro-edt-ds">
                                                      <button type="submit" class="btn btn-primary waves-effect waves-light m-r-10">Save
                                                      </button>
                                                      <button type="button" class="btn btn-warning waves-effect waves-light">Discard
                                                      </button>
                                                  </div>
                                              </div>
                                          </div>
                                        @endif
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('script-extra')

@endsection

resources/views/resellers/index.blade.php
@extends('layouts.default')

@section('content')
    <div class="product-status mg-tb-15">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="product-status-wrap">
                        <h4>Reseller</h4>
                        <div class="add-product">
                            <a href="{{ route('reseller.create') }}">Add Reseller</a>
                        </div>
                        <table id="myTable">
                            <thead>
                                <tr>
                                    <th>Nama</th>
                                    <th>Email</th>
                                    <th>Tipe Reseller</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                            @foreach($resellers as $key => $reseller)
                                <tr>
                                    <td>{{ $reseller->name }}</td>
                                    <td>{{ $reseller->email }}</td>
                                    <td>{{ $reseller->reseller_type_name }}</td>
                                    <td>
                                        {{-- <button class="pd-setting">{{ $reseller->status }}</button> --}}
                                        {{ $reseller->status }}
                                    </td>
                                    @if (Auth::user()->user_type != 'finance')
                                      <td>
                                        <button data-toggle="tooltip" title="Edit" class="pd-setting-ed"><a href="{{ route('reseller.edit', $reseller->id) }}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a></button>
                                          <a href="{{ url('reseller/destroy',$reseller->id) }}" onclick="return confirm('Are you sure to delete?');"><button data-toggle="tooltip" title="Trash" class="pd-setting-ed"><i class="fa fa-trash-o" aria-hidden="true"></i></button></a>
                                        <form id="delete-form{{ $reseller->id }}" action="{{ route('reseller.destroy', $reseller->id) }}" method="POST" style="display: none;">
                                              @csrf
                                              <input type="hidden" name="_method" value="DELETE">
                                        </form>
                                          @if($reseller->status == "active")
                                              <button data-toggle="tooltip" title="Disable Reseller" class="btn btn-custon-rounded-three btn-danger"><a href="{{url('disable-user/'.$reseller->id)}}"><i class="fa fa-times adminpro-danger-error" aria-hidden="true"></i></a></button>
                                          @else
                                              <button data-toggle="tooltip" title="Enable Reseller" class="btn btn-custon-rounded-three btn-success"><a href="{{url('enable-user/'.$reseller->id)}}"><i class="fa fa-check adminpro-checked-pro" aria-hidden="true"></i></a></button>
                                          @endif
                                      </td>
                                    @endif
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        {{--<div class="custom-pagination">--}}
                        {{--<nav aria-label="Page navigation example">--}}
                        {{--<ul class="pagination">--}}
                        {{--<li class="page-item"><a class="page-link" href="#">Previous</a></li>--}}
                        {{--<li class="page-item"><a class="page-link" href="#">1</a></li>--}}
                        {{--<li class="page-item"><a class="page-link" href="#">2</a></li>--}}
                        {{--<li class="page-item"><a class="page-link" href="#">3</a></li>--}}
                        {{--<li class="page-item"><a class="page-link" href="#">Next</a></li>--}}
                        {{--</ul>--}}
                        {{--</nav>--}}
                        {{--</div>--}}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script-extra')
    <script>
        $(document).ready( function () {
            $('#myTable').DataTable()
        } )
    </script>
@endsection