routes/web.php
<?php

use App\Product;
use App\User;
use App\Order;
use App\Wallet;
use App\Frontslide;

/*
|----------------------------- ---------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/getCity', 'FrontController@getCity')->name('rajaOngkir.getCity');
Route::get('/getSubdistrict', 'FrontController@getSubdistrict')->name('rajaOngkir.getSubdistrict');
Route::get('/getCost', 'FrontController@getCost')->name('rajaOngkir.getCost');

Route::prefix('/member')->group(function (){
  Route::resource('/', 'MemberController');
    Route::get('/home', 'MemberController@index');
    Route::get('/catalog', 'MemberController@catalog');
    Route::get('/product', 'MemberController@product');

    Route::get('/productdetail/{id}', 'MemberController@productdetail');
    Route::get('/productdetail/{id}/productasset', 'MemberController@productasset');
    Route::get('/detailproduct/{id}', 'MemberController@detailproduct');
    Route::get('/setting', 'MemberController@setting');
    Route::get('/setting/profile', 'MemberController@profile');
    Route::get('/setting/password', 'MemberController@password');
    Route::get('/setting/bank', 'MemberController@bank');
    Route::get('/setting/profiletoko', 'MemberController@profiletoko');
    Route::get('/setting/logo', 'MemberController@logo');

    Route::get('/setting/frontslide', 'MemberController@frontslide');

    Route::post('/setting/frontslidepost', 'MemberController@frontslidepost');
    Route::get('/setting/frontslidel/{id}', function($id){
      $data = Frontslide::findOrFail($id);
      File::delete('images/slides/' . @$data->picture);
      $data->delete();
      return redirect()->back()->with('success','B erhasil Delete Data');
      });

    Route::post('/setting/logoupdate', 'MemberController@logoupdate')->name('logoupdate');

    Route::get('/team', 'MemberController@team');

    Route::get('/teamadd', 'MemberController@teamadd');

    Route::get('/gajian', 'MemberController@gajian');
    Route::get('/gajianout', 'MemberController@gajianout');

    Route::get('/request', 'MemberController@request');

    Route::get('/coupon', 'MemberController@coupon');
    Route::get('/order', 'MemberController@order');
    Route::get('/landingpage', 'MemberController@landingpage');
    Route::get('/apps', 'MemberController@apps');

    Route::prefix('/order')->group(function (){
      Route::resource('/', 'MemberOrderController');
        Route::get('/prospek', 'MemberOrderController@prospek');
        Route::get('/catalog', 'MemberOrderController@catalog');
        Route::get('/detail/{id}', 'MemberOrderController@detail');


       });
   });
Route::prefix('/admin')->group(function (){
  Route::resource('/', 'AdminController');
    Route::get('/home', 'MemberController@index');
    Route::get('/catalog', 'MemberController@catalog');
    Route::get('/product', 'MemberController@product');

    Route::get('/productdetail/{id}', 'MemberController@productdetail');

    Route::get('/detailproduct/{id}', 'MemberController@detailproduct');
    Route::get('/setting', 'MemberController@setting');
    Route::get('/team', 'MemberController@team');

    Route::get('/teamadd', 'MemberController@teamadd');

    Route::get('/gajian', 'MemberController@gajian');
    Route::get('/coupon', 'MemberController@coupon');
    Route::get('/order', 'MemberController@order');
    Route::get('/landingpage', 'MemberController@landingpage');
    Route::get('/apps', 'MemberController@apps');

    Route::prefix('/order')->group(function (){
      Route::resource('/', 'AdminOrderController');
        Route::get('/prospek', 'AdminOrderController@prospek');
        Route::get('/catalog', 'AdminOrderController@catalog');
        Route::get('/detail/{id}', 'AdminOrderController@catalog');


       });
   });


Route::prefix('/')->group(function (){
   Route::resource('/','FrontController');
   Route::get('/productdetail/{id}', 'FrontController@productdetail');
   Route::get('/front/category/{id}', 'FrontController@productcategory');

   /*
   Route::prefix('product')->group(function (){
            Route::resource('/','AdminProductController');
        });
        */
   });

Route::prefix('/test')->group(function (){
   Route::resource('/','TestController');
   Route::get('/create', 'TestController@create');
   });

Route::get('/admin', function () {
    return view('auth.login');
});


Route::get('/home', 'HomeController@index')->name('home');
Route::get('/wallet/reseller/{id}', 'WalletController@resellerWallet')->name('wallet.reseller');
Route::get('/wallet/admin', 'WalletController@adminWallet')->name('wallet.admin');
Route::get('/wallet/history', 'WalletController@historyWallet')->name('wallet.history');
Route::post('/wallet/update-status/{id}', 'WalletController@statusWallet')->name('wallet.status');
Route::get('/order/prospect', 'OrderController@prospect')->name('order.prospect');
Route::get('/order/confirm', 'OrderController@confirm')->name('order.confirm');
Route::get('/order/packing', 'OrderController@packing')->name('order.packing');
Route::get('/order/delivering', 'OrderController@delivering')->name('order.delivering');
Route::get('/order/success', 'OrderController@success')->name('order.success');
Route::get('/order/tracking', 'OrderController@tracking')->name('order.tracking');

Route::get('/order/detail/{id}', 'OrderController@detail')->name('order.detail');

Route::post('/order/track', 'OrderController@trackOrder')->name('order.trackOrder');
Route::get('/orders','OrderController@index')->name('order.sell');
Route::get('/product/destroy/{id}','ProductController@destroy');
Route::get('/reseller/destroy/{id}','ResellerController@destroy');

Route::resource('/product', 'ProductController');

Route::resource('/reseller', 'ResellerController');
Route::resource('/wallet', 'WalletController');
Route::resource('/resellerPackage', 'ResellerPackageController');
Route::resource('/order', 'OrderController');
Route::resource('/category', 'CategoryController');
Route::resource('/catalog', 'CatalogController');
Route::resource('/coupon', 'CouponController');
Route::resource('/resellerDashboard', 'ResellerDashboardController');
Route::resource('/user', 'UserController');
Route::resource('/bank', 'BankAccountController');
Route::resource('/asset', 'AssetController');
Route::resource('/stock', 'StockController');


Route::get('/disable-product/{id}', function($id){
  $product = Product::findOrFail($id);
  $product->status = 'inactive';
  $product->save();
  return redirect()->back();
});

Route::get('/enable-product/{id}', function($id){
  $product = Product::findOrFail($id);
  $product->status = 'active';
  $product->save();
  return redirect()->back();
});

Route::get('/disable-user/{id}', function($id){
  $user = User::findOrFail($id);
  $user->status = 'inactive';
  $user->save();
  return redirect()->back();
});

Route::get('/enable-user/{id}', function($id){
  $user = User::findOrFail($id);
  $user->status = 'active';
  $user->save();
  return redirect()->back();
});

Route::get('/prospect/{id}', function($id){
  $order = Order::findOrFail($id);
  $user->order_status = 'prospect';
  $order->save();
  return redirect()->save();
});

Route::get('/pending/{id}', function($id){
  $order = Order::findOrFail($id);
  $order->order_status = 'pending';
  $order->save();
  return redirect()->back();
});

Route::get('/konfirmasi/{id}', function($id){
  $order = Order::findOrFail($id);
  $order->order_status = 'processing';
  $order->save();
  // dd($order);

  return redirect()->back();
});

Route::get('/pembayaranDiterima/{id}', function($id){
  $order = Order::findOrFail($id);
  $order->order_status = 'paid';
  $order->save();
  return redirect()->back();
});

Route::get('/packing/{id}', function($id){
  $order = Order::findOrfail($id);
  $order->order_status = 'packing';
  $order->save();
  return redirect()->back();
});

Route::get('/pengiriman/{id}', function($id){
  $order = Order::findOrFail($id);
  $order->order_status = 'delivering';
  $order->save();
  return redirect()->back();
});

Route::get('/diTerima/{id}', function($id){

  $order = Order::findOrFail($id);
  $order->order_status = 'success';
  $order->save();

  $orderdetail = \DB::table('order_details')->where('order_id',$id)->sum('profit');
  $wallet = New Wallet();
  $wallet->user_id = $order->reseller_id;
  $wallet->balanced = $orderdetail;
  $wallet->type = 'Credit';
  $wallet->desc = "Profit Dari Penjualan Barang";
  $wallet->order_id = @$order->id;
  $wallet->save();

  return redirect()->back();

});

app/Coupon.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Coupon extends Model
{
    protected $fillable = [
        'product_id',
        'title',
        'discount',
        'start_date',
        'end_date',
        'limit'
    ];
}

app/Http/Controllers/CouponController.php
<?php

namespace App\Http\Controllers;

use App\Coupon;
use App\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CouponController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        $coupons = Coupon::select('coupons.*', 'products.name as product_name')
            ->leftJoin('products', 'products.id', '=', 'coupons.product_id')
            ->get();
        return view('coupons.index', compact('coupons'));
    }

    
    public function create()
    {
        $products = Product::select('products.*')
            ->leftJoin('shop_products', 'products.id', '=', 'shop_products.product_id')
            ->where('shop_products.user_id', Auth::user()->id)
            ->get();

        return view('coupons.create', compact('products'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'product_id' => 'required',
            'discount' => 'required',
            'start_date' => 'required',
            'end_date' => 'required',
        ]);

        Coupon::create($request->all());

        return redirect()->route('coupon.index');
    }

    
    public function show($id)
    {
        //
    }

    
    public function edit($id)
    {
        $data = Coupon::findOrFail($id);

        return view('coupons.edit', compact('data'));
    }

    
    public function update(Request $request, $id)
    {
        $coupon = Coupon::findOrFail($id);

        $this->validate($request, [
            'product_id' => 'required',
            'discount' => 'required',
            'start_date' => 'required',
            'end_date' => 'required',
        ]);

        $input = $request->all();
        $coupon->fill($input)->save();

        return redirect()->route('coupon.index');
    }

    
    public function destroy($id)
    {
        $coupon = Coupon::find($id);
        $coupon->delete();

        return redirect()->route('coupon.index');
    }
}

resources/views/coupons/create.blade.php
@extends('layouts.default')

@section('content')
    <div class="single-product-tab-area mg-tb-15">
        <!-- Single pro tab review Start-->
        <div class="single-pro-review-area">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="review-tab-pro-inner">
                            <ul id="myTab3" class="tab-review-design">
                                <li class="active"><a href="#description"><i class="fa fa-pencil" aria-hidden="true"></i> Add New Kupon</a></li>
                            </ul>
                            <div id="myTabContent" class="tab-content custom-product-edit">
                                <div class="product-tab-list tab-pane fade active in" id="description">

                                    <form method="POST" action="{{ route('coupon.store') }}">
                                        @csrf
                                        <div class="row">
                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                <div class="review-content-section">
                                                    <div class="form-group data-custon-pick" id="data_1">
                                                        <label>Nama </label>
                                                        <div class="input-group ">
                                                            <span class="input-group-addon"><i class="fa fa-edit"></i></span>
                                                            <input type="text" name="name" class="form-control" placeholder="Nama" value="{{ old('name') }}">
                                                        </div>
                                                    </div>
                                                    <label>Produk</label>
                                                    <select name="product_id" class="form-control pro-edt-select form-control-primary">
                                                        @foreach($products as $key => $value)
                                                            <option value="{{ $value->id }}">{{ $value->name }}</option>
                                                        @endforeach
                                                    </select>
                                                    <div class="form-group data-custon-pick" id="data_1">
                                                        <label>Berlaku Mulai</label>
                                                        <div class="input-group date">
                                                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                                            <input type="text" name="start_date" class="form-control datepicker" value="{{ old('start_date') }}">
                                                        </div>
                                                    </div>
                                                    <div class="form-group data-custon-pick" id="data_1">
                                                        <label>Berlaku Sampai</label>
                                                        <div class="input-group date">
                                                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                                            <input type="text" name="end_date" class="form-control datepicker" value="{{ old('end_date') }}">
                                                        </div>
                                                    </div>
                                                    <div class="form-group data-custon-pick" id="data_1">
                                                        <label>Limit </label>
                                                        <div class="input-group">
                                                            <span class="input-group-addon"><i class="fa fa-edit"></i></span>
                                                            <input type="text" name="limit" class="form-control" placeholder="Kosongkan jika tidak ada batas" value="{{ old('limit') }}">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                <div class="text-center mg-b-pro-edt custom-pro-edt-ds">
                                                    <button type="submit" class="btn btn-primary waves-effect waves-light m-r-10">Save
                                                    </button>
                                                    <a href="{{ route('coupon.index') }}"><button type="button" class="btn btn-warning waves-effect waves-light">Discard
                                                        </button></a>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('script-extra')

@endsection

resources/views/coupons/edit.blade.php
@extends('layouts.default')

@section('content')
    <div class="single-product-tab-area mg-tb-15">
        <!-- Single pro tab review Start-->
        <div class="single-pro-review-area">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="review-tab-pro-inner">
                            <ul id="myTab3" class="tab-review-design">
                                <li class="active"><a href="#description"><i class="fa fa-pencil" aria-hidden="true"></i> Add New Kupon</a></li>
                            </ul>
                            <div id="myTabContent" class="tab-content custom-product-edit">
                                <div class="product-tab-list tab-pane fade active in" id="description">

                                    <form method="POST" action="{{ route('coupon.update', $data->id) }}">
                                        @csrf
                                        <input type="hidden" name="_method" value="PUT">
                                        <div class="row">
                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                <div class="review-content-section">
                                                    <div class="form-group data-custon-pick" id="data_1">
                                                        <label>Nama </label>
                                                        <div class="input-group ">
                                                            <span class="input-group-addon"><i class="fa fa-edit"></i></span>
                                                            <input type="text" name="name" class="form-control" placeholder="Nama" value="{{ $data->name }}">
                                                        </div>
                                                    </div>
                                                    <label>Produk</label>
                                                    <select name="product_id" class="form-control pro-edt-select form-control-primary">
                                                        @foreach($products as $key => $value)
                                                            @if ($value->id == $data->product_id)
                                                                <option value="{{ $value->id }}" selected>{{ $value->name }}</option>
                                                            @else
                                                                <option value="{{ $value->id }}">{{ $value->name }}</option>
                                                            @endif
                                                        @endforeach
                                                    </select>
                                                    <div class="form-group data-custon-pick" id="data_1">
                                                        <label>Berlaku Mulai</label>
                                                        <div class="input-group date">
                                                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                                            <input type="text" name="start_date" class="form-control datepicker" value="{{ $data->start_date }}">
                                                        </div>
                                                    </div>
                                                    <div class="form-group data-custon-pick" id="data_1">
                                                        <label>Berlaku Sampai</label>
                                                        <div class="input-group date">
                                                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                                            <input type="text" name="end_date" class="form-control datepicker" value="{{ $data->end_date }}">
                                                        </div>
                                                    </div>
                                                    <div class="form-group data-custon-pick" id="data_1">
                                                        <label>Limit </label>
                                                        <div class="input-group">
                                                            <span class="input-group-addon"><i class="fa fa-edit"></i></span>
                                                            <input type="text" name="limit" class="form-control" placeholder="Kosongkan jika tidak ada batas" value="{{ $data->limit }}">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                <div class="text-center mg-b-pro-edt custom-pro-edt-ds">
                                                    <button type="submit" class="btn btn-primary waves-effect waves-light m-r-10">Save
                                                    </button>
                                                    <a href="{{ route('coupon.index') }}"><button type="button" class="btn btn-warning waves-effect waves-light">Discard
                                                        </button></a>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('script-extra')

@endsection

resources/views/coupons/index.blade.php
@extends('layouts.default')

@section('content')
    <div class="product-status mg-tb-15">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="product-status-wrap">
                        <h4>Kupon</h4>
                        <div class="add-product">
                            <a href="{{ route('coupon.create') }}">Add Kupon</a>
                        </div>
                        <table id="myTable">
                            <thead>
                            <tr>
                                <th>Product</th>
                                <th>Discount</th>
                                <th>Start Date</th>
                                <th>End Date</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($coupons as $key => $coupon)
                                <tr>
                                    <td>{{ $coupon->product_name }}</td>
                                    <td>{{ $coupon->discount }} %</td>
                                    <td>{{ $coupon->start_date }}</td>
                                    <td>{{ $coupon->end_date }}</td>
                                    <td>
                                        <button data-toggle="tooltip" title="Edit" class="pd-setting-ed"><a href="{{ route('coupon.edit', $coupon->id) }}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a></button>
                                        <a href="{{ route('coupon.destroy', $coupon->id) }}" onclick="event.preventDefault(); document.getElementById('delete-form{{ $coupon->id }}').submit();"><button data-toggle="tooltip" title="Trash" class="pd-setting-ed"><i class="fa fa-trash-o" aria-hidden="true"></i></button></a>
                                        <form id="delete-form{{ $coupon->id }}" action="{{ route('coupon.destroy', $coupon->id) }}" method="POST" style="display: none;">
                                            @csrf
                                            <input type="hidden" name="_method" value="DELETE">
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script-extra')
    <script>
        $(document).ready( function () {
            $('#myTable').DataTable()
        } )
    </script>
@endsection