routes/web.php
<?php

use App\Product;
use App\User;
use App\Order;
use App\Wallet;
use App\Frontslide;

/*
|----------------------------- ---------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/getCity', 'FrontController@getCity')->name('rajaOngkir.getCity');
Route::get('/getSubdistrict', 'FrontController@getSubdistrict')->name('rajaOngkir.getSubdistrict');
Route::get('/getCost', 'FrontController@getCost')->name('rajaOngkir.getCost');

Route::prefix('/member')->group(function (){
  Route::resource('/', 'MemberController');
    Route::get('/home', 'MemberController@index');
    Route::get('/catalog', 'MemberController@catalog');
    Route::get('/product', 'MemberController@product');

    Route::get('/productdetail/{id}', 'MemberController@productdetail');
    Route::get('/productdetail/{id}/productasset', 'MemberController@productasset');
    Route::get('/detailproduct/{id}', 'MemberController@detailproduct');
    Route::get('/setting', 'MemberController@setting');
    Route::get('/setting/profile', 'MemberController@profile');
    Route::get('/setting/password', 'MemberController@password');
    Route::get('/setting/bank', 'MemberController@bank');
    Route::get('/setting/profiletoko', 'MemberController@profiletoko');
    Route::get('/setting/logo', 'MemberController@logo');

    Route::get('/setting/frontslide', 'MemberController@frontslide');

    Route::post('/setting/frontslidepost', 'MemberController@frontslidepost');
    Route::get('/setting/frontslidel/{id}', function($id){
      $data = Frontslide::findOrFail($id);
      File::delete('images/slides/' . @$data->picture);
      $data->delete();
      return redirect()->back()->with('success','B erhasil Delete Data');
      });

    Route::post('/setting/logoupdate', 'MemberController@logoupdate')->name('logoupdate');

    Route::get('/team', 'MemberController@team');

    Route::get('/teamadd', 'MemberController@teamadd');

    Route::get('/gajian', 'MemberController@gajian');
    Route::get('/gajianout', 'MemberController@gajianout');

    Route::get('/request', 'MemberController@request');

    Route::get('/coupon', 'MemberController@coupon');
    Route::get('/order', 'MemberController@order');
    Route::get('/landingpage', 'MemberController@landingpage');
    Route::get('/apps', 'MemberController@apps');

    Route::prefix('/order')->group(function (){
      Route::resource('/', 'MemberOrderController');
        Route::get('/prospek', 'MemberOrderController@prospek');
        Route::get('/catalog', 'MemberOrderController@catalog');
        Route::get('/detail/{id}', 'MemberOrderController@detail');


       });
   });
Route::prefix('/admin')->group(function (){
  Route::resource('/', 'AdminController');
    Route::get('/home', 'MemberController@index');
    Route::get('/catalog', 'MemberController@catalog');
    Route::get('/product', 'MemberController@product');

    Route::get('/productdetail/{id}', 'MemberController@productdetail');

    Route::get('/detailproduct/{id}', 'MemberController@detailproduct');
    Route::get('/setting', 'MemberController@setting');
    Route::get('/team', 'MemberController@team');

    Route::get('/teamadd', 'MemberController@teamadd');

    Route::get('/gajian', 'MemberController@gajian');
    Route::get('/coupon', 'MemberController@coupon');
    Route::get('/order', 'MemberController@order');
    Route::get('/landingpage', 'MemberController@landingpage');
    Route::get('/apps', 'MemberController@apps');

    Route::prefix('/order')->group(function (){
      Route::resource('/', 'AdminOrderController');
        Route::get('/prospek', 'AdminOrderController@prospek');
        Route::get('/catalog', 'AdminOrderController@catalog');
        Route::get('/detail/{id}', 'AdminOrderController@catalog');


       });
   });


Route::prefix('/')->group(function (){
   Route::resource('/','FrontController');
   Route::get('/productdetail/{id}', 'FrontController@productdetail');
   Route::get('/front/category/{id}', 'FrontController@productcategory');

   /*
   Route::prefix('product')->group(function (){
            Route::resource('/','AdminProductController');
        });
        */
   });

Route::prefix('/test')->group(function (){
   Route::resource('/','TestController');
   Route::get('/create', 'TestController@create');
   });

Route::get('/admin', function () {
    return view('auth.login');
});


Route::get('/home', 'HomeController@index')->name('home');
Route::get('/wallet/reseller/{id}', 'WalletController@resellerWallet')->name('wallet.reseller');
Route::get('/wallet/admin', 'WalletController@adminWallet')->name('wallet.admin');
Route::get('/wallet/history', 'WalletController@historyWallet')->name('wallet.history');
Route::post('/wallet/update-status/{id}', 'WalletController@statusWallet')->name('wallet.status');
Route::get('/order/prospect', 'OrderController@prospect')->name('order.prospect');
Route::get('/order/confirm', 'OrderController@confirm')->name('order.confirm');
Route::get('/order/packing', 'OrderController@packing')->name('order.packing');
Route::get('/order/delivering', 'OrderController@delivering')->name('order.delivering');
Route::get('/order/success', 'OrderController@success')->name('order.success');
Route::get('/order/tracking', 'OrderController@tracking')->name('order.tracking');

Route::get('/order/detail/{id}', 'OrderController@detail')->name('order.detail');

Route::post('/order/track', 'OrderController@trackOrder')->name('order.trackOrder');
Route::get('/orders','OrderController@index')->name('order.sell');
Route::get('/product/destroy/{id}','ProductController@destroy');
Route::get('/reseller/destroy/{id}','ResellerController@destroy');

Route::resource('/product', 'ProductController');

Route::resource('/reseller', 'ResellerController');
Route::resource('/wallet', 'WalletController');
Route::resource('/resellerPackage', 'ResellerPackageController');
Route::resource('/order', 'OrderController');
Route::resource('/category', 'CategoryController');
Route::resource('/catalog', 'CatalogController');
Route::resource('/coupon', 'CouponController');
Route::resource('/resellerDashboard', 'ResellerDashboardController');
Route::resource('/user', 'UserController');
Route::resource('/bank', 'BankAccountController');
Route::resource('/asset', 'AssetController');
Route::resource('/stock', 'StockController');


Route::get('/disable-product/{id}', function($id){
  $product = Product::findOrFail($id);
  $product->status = 'inactive';
  $product->save();
  return redirect()->back();
});

Route::get('/enable-product/{id}', function($id){
  $product = Product::findOrFail($id);
  $product->status = 'active';
  $product->save();
  return redirect()->back();
});

Route::get('/disable-user/{id}', function($id){
  $user = User::findOrFail($id);
  $user->status = 'inactive';
  $user->save();
  return redirect()->back();
});

Route::get('/enable-user/{id}', function($id){
  $user = User::findOrFail($id);
  $user->status = 'active';
  $user->save();
  return redirect()->back();
});

Route::get('/prospect/{id}', function($id){
  $order = Order::findOrFail($id);
  $user->order_status = 'prospect';
  $order->save();
  return redirect()->save();
});

Route::get('/pending/{id}', function($id){
  $order = Order::findOrFail($id);
  $order->order_status = 'pending';
  $order->save();
  return redirect()->back();
});

Route::get('/konfirmasi/{id}', function($id){
  $order = Order::findOrFail($id);
  $order->order_status = 'processing';
  $order->save();
  // dd($order);

  return redirect()->back();
});

Route::get('/pembayaranDiterima/{id}', function($id){
  $order = Order::findOrFail($id);
  $order->order_status = 'paid';
  $order->save();
  return redirect()->back();
});

Route::get('/packing/{id}', function($id){
  $order = Order::findOrfail($id);
  $order->order_status = 'packing';
  $order->save();
  return redirect()->back();
});

Route::get('/pengiriman/{id}', function($id){
  $order = Order::findOrFail($id);
  $order->order_status = 'delivering';
  $order->save();
  return redirect()->back();
});

Route::get('/diTerima/{id}', function($id){

  $order = Order::findOrFail($id);
  $order->order_status = 'success';
  $order->save();

  $orderdetail = \DB::table('order_details')->where('order_id',$id)->sum('profit');
  $wallet = New Wallet();
  $wallet->user_id = $order->reseller_id;
  $wallet->balanced = $orderdetail;
  $wallet->type = 'Credit';
  $wallet->desc = "Profit Dari Penjualan Barang";
  $wallet->order_id = @$order->id;
  $wallet->save();

  return redirect()->back();

});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
        'name',
        'slug',
        'brand',
        'sku',
        'category_id',
//        'agent_price',
        'seller_price',
        'profit',
        'profit_limit',
        'discount',
        'weight',
        'unit',
        'description',
        'main_image',
        'status',
    ];

    public function category(){
      return $this->belongsTo(Category::class);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Product;
use App\ProductPrice;
use App\ProductStock;
use App\ResellerPackage;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class ProductController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();

        return view('products.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        $resellerPackages = ResellerPackage::all();

        return view('products.create', compact('categories', 'resellerPackages'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $slug = Str::slug($request->name);
        $this->validate($request, [

        ]);

        $request->merge([
            'slug' => $slug,
            'status' => 'active',
            'unit' => 'gram',
        ]);

        $name = '';
        $destinationPath = public_path('/images/products/');

        if ($request->file('images')) {
            $img = $request->file('images');
            $name = 'products-'.time() . '.'. $img->getClientOriginalExtension();
            $img->move($destinationPath, $name);
        }

        $request->merge([
            'main_image' => $name
        ]);

        $data = Product::create($request->all());

        foreach ($request->agent_price as $key => $value) {
                //dd($request->agent_price);
            ProductPrice::create([
                'product_id' => $data->id,
                'reseller_package_id' => $request->reseller_package_id[$key],
                'agent_price' => $value,
            ]);
        }

        $stock = ProductStock::create([
            'product_id' => $data->id,
            'stock' => $request->quantity
        ]);

        return redirect()->route('product.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Product::findOrFail($id);
        $stocks = ProductStock::where('product_id', '=', $id)->get();
        return view('products.show', compact('data', 'stocks'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Product::select('products.*', 'categories.name as category_name')
            ->leftJoin('categories', 'categories.id', '=', 'products.category_id')
            ->where('products.id', $id)
            ->first();

        $stock = ProductStock::where('product_id', '=', $id)->get();
        $categories = Category::all();
        // $resellerPackages = ResellerPackage::all();
        $resellerPackages = ProductPrice::where('product_id', '=', $id)->get();
      //dd($resellerPackages);
        if($data == null || $resellerPackages->first() == null || $categories == null)
          return "Data Kosong";
        else
          return view('products.edit', compact('data', 'stock', 'categories', 'resellerPackages'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product = Product::findOrFail($id);

//         $this->validate($request, [
//             'name' => 'required',
//             'brand' => 'required',
// //            'agent_price' => 'required',
// //            'selling_price' => 'required',
// //            'profit' => 'required',
// //            'discount' => 'required',
// //            'description' => 'required',
//             'category' => 'required'
//         ]);

        $input = $request->all();

        $name = '';
        $destinationPath = public_path('/images/products/');

        if ($request->file('images')) {
            $img = $request->file('images');
            $name = 'products-'.time() . '.'. $img->getClientOriginalExtension();
            $img->move($destinationPath, $name);
            $product->main_image = $name;
        }

        $product->fill($input)->save();
        $product->save();

        foreach ($request->agent_price as $key => $value) {
          $price = ProductPrice::where([
            ['product_id', '=', $id],
            ['reseller_package_id', '=', $request->reseller_package_id[$key]],
            ])->first();
          $price->agent_price = $value;
          $price->save();
        }

        return redirect()->back();
        // return redirect()->route('product.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::find($id);
        $product->delete();

        return redirect()->route('product.index');
    }
}

resources/views/products/index-ex.blade.php
@extends('layouts.default')

@section('content')
    <div class="product-status mg-tb-15">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="product-status-wrap">
                        <h4>Products List</h4>
                        <div class="add-product">
                            <a href="{{ route('product.create') }}">Add Product</a>
                        </div>
                        <table id="myTable">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Brand</th>
                                    <th>Status</th>
                                    <th>Purchases</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($products as $key => $product)
                                    <tr>
                                        <td>{{ $product->name }}</td>
                                        <td>{{ $product->brand }}</td>
                                        <td>
                                            <button class="pd-setting">{{ $product->status }}</button>
                                        </td>
                                        <td>0</td>
                                        <td>
                                            <button data-toggle="tooltip" title="Edit" class="pd-setting-ed"><a href="{{ route('product.edit', $product->id) }}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a></button>
                                            <button data-toggle="tooltip" title="Trash" class="pd-setting-ed"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        {{--<div class="custom-pagination">--}}
                            {{--<nav aria-label="Page navigation example">--}}
                                {{--<ul class="pagination">--}}
                                    {{--<li class="page-item"><a class="page-link" href="#">Previous</a></li>--}}
                                    {{--<li class="page-item"><a class="page-link" href="#">1</a></li>--}}
                                    {{--<li class="page-item"><a class="page-link" href="#">2</a></li>--}}
                                    {{--<li class="page-item"><a class="page-link" href="#">3</a></li>--}}
                                    {{--<li class="page-item"><a class="page-link" href="#">Next</a></li>--}}
                                {{--</ul>--}}
                            {{--</nav>--}}
                        {{--</div>--}}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script-extra')
    <script>
        $(document).ready( function () {
            $('#myTable').DataTable()
        } )
    </script>
@endsection

resources/views/products/index.blade.php
@extends('layouts.default')

@section('content')
    <div class="product-status mg-tb-15">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="product-status-wrap">
                        <div class="element-header">
                            <h4>Products</h4>
                            <div class="add-product">
                                <a href="{{ route('product.create') }}">Add Product</a>
                            </div>
                        </div>
                        <ul id="myTab3" class="tab-review-design">
                            <li class="active"><a href="#description">All</a></li>
                            <li><a href="#activeProduct">Active</a></li>
                            <li><a href="#inactiveProduct">Not Active</a></li>
                            {{--<li><a href="#INFORMATION"><i class="fa fa-commenting" aria-hidden="true"></i> Review</a></li>--}}
                        </ul>
                        <div id="myTabContent" class="tab-content custom-product-edit">
                        <div  class="product-tab-list tab-pane fade active in" id="description">
                          <table id="myTable" class="table table-bordered table-striped">
                              <thead>
                                  <tr>
                                      <th>Name</th>
                                      <th>Brand</th>
                                      <th>Status</th>
                                      <th>Purchases</th>
                                      <th>Action</th>
                                  </tr>
                              </thead>
                              <tbody>
                                  @foreach($products as $key => $product)
                                      <tr>
                                          <td>
                                              {{--<img src="{!! asset('img/logo/logo.png') !!}" alt="">--}}
                                              {{ $product->name }}</td>
                                          <td>{{ $product->brand }}</td>
                                          <td>
                                              {{-- <button class="pd-setting">{{ $product->status }}</button> --}}
                                              {{ $product->status }}
                                          </td>
                                          <td>0</td>
                                          <td>
                                              <button data-toggle="tooltip" title="Detail" class="pd-setting-ed bg-pink"><a href="{{ route('product.edit', $product->id) }}"><i class="fa fa-file" aria-hidden="true"></i></a></button>
                                              <button data-toggle="tooltip" title="Customer" class="pd-setting-ed bg-cream"><a href="{{route('order.index')}}"><i class="fa fa-shopping-cart" aria-hidden="true"></i></a></button>
                                              <button data-toggle="tooltip" title="Asset" class="pd-setting-ed bg-green"><a href="{{ route('asset.show', $product->id) }}"><i class="fa fa-image" aria-hidden="true"></i></a></button>
                                              <button data-toggle="tooltip" title="Stock" class="pd-setting-ed bg-yellow"><a href="{{route('stock.show', $product->id)}}"><i class="fa fa-archive" aria-hidden="true"></i></a></button>
                                              <button data-toggle="tooltip" title="Show" class="pd-setting-ed bg-orange"><a href="{{ route('product.show', $product->id) }}"><i class="fa fa-link" aria-hidden="true"></i></a></button>
                                              @if (Auth::user()->user_type != 'finance')
                                                @if ($product->status == "active")
                                                  <button data-toggle="tooltip" title="Disable Product" class="btn btn-custon-rounded-three btn-danger"><a href="{{url('disable-product/'.$product->id)}}"><i class="fa fa-times adminpro-danger-error" aria-hidden="true"></i></a></button>
                                                @else
                                                  <button data-toggle="tooltip" title="Enable Product" class="btn btn-custon-rounded-three btn-success"><a href="{{url('enable-product/'.$product->id)}}"><i class="fa fa-check adminpro-checked-pro" aria-hidden="true"></i></a></button>
                                                @endif
                                              @endif
                                                <a type="button" class="btn btn-custon-rounded-three btn-warning" onclick="return confirm('Are you sure to delete?')" href="{{url('product/destroy',$product->id)}}"><i class="fa fa-trash" aria-hidden="true"></i></a>
                                          </td>
                                      </tr>
                                  @endforeach
                              </tbody>
                          </table>
                        </div>
                        <div class="product-tab-list tab-pane fade" id="activeProduct">
                            <table id="myTable2" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Brand</th>
                                        <th>Status</th>
                                        <th>Purchases</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($products as $key => $product)
                                        @if ($product->status == "active")
                                        <tr>
                                            <td>
                                                {{--<img src="{!! asset('img/logo/logo.png') !!}" alt="">--}}
                                                {{ $product->name }}</td>
                                            <td>{{ $product->brand }}</td>
                                            <td>
                                                {{-- <button class="pd-setting">{{ $product->status }}</button> --}}
                                                {{ $product->status }}
                                            </td>
                                            <td>0</td>
                                            <td>
                                                <button data-toggle="tooltip" title="Detail" class="pd-setting-ed bg-pink"><a href="{{ route('product.edit', $product->id) }}"><i class="fa fa-file" aria-hidden="true"></i></a></button>
                                                {{-- <button data-toggle="tooltip" title="Seller" class="pd-setting-ed bg-cream"><a href="{{route('order.index')}}"><i class="fa fa-shopping-cart" aria-hidden="true"></i></a></button> --}}
                                                <button data-toggle="tooltip" title="Customer" class="pd-setting-ed bg-red"><a href="{{route('order.index')}}"><i class="fa fa-shopping-cart" aria-hidden="true"></i></a></button>
                                                <button data-toggle="tooltip" title="Asset" class="pd-setting-ed bg-green"><a href="{{ route('asset.show', $product->id) }}"><i class="fa fa-image" aria-hidden="true"></i></a></button>
                                                <button data-toggle="tooltip" title="Stock" class="pd-setting-ed bg-yellow"><a href="{{route('stock.index')}}"><i class="fa fa-archive" aria-hidden="true"></i></a></button>
                                                <button data-toggle="tooltip" title="Show" class="pd-setting-ed bg-orange"><a href="{{ route('product.show', $product->id) }}"><i class="fa fa-link" aria-hidden="true"></i></a></button>
                                                @if (Auth::user()->user_type != 'finance')
                                                  @if ($product->status == "active")
                                                    <button data-toggle="tooltip" title="Disable Product" class="btn btn-custon-rounded-three btn-danger"><a href="{{url('disable-product/'.$product->id)}}"><i class="fa fa-times adminpro-danger-error" aria-hidden="true"></i></a></button>
                                                  @else
                                                    <button data-toggle="tooltip" title="Enable Product" class="btn btn-custon-rounded-three btn-success"><a href="{{url('enable-product/'.$product->id)}}"><i class="fa fa-check adminpro-checked-pro" aria-hidden="true"></i></a></button>
                                                  @endif
                                                @endif
                                            </td>
                                        </tr>
                                    @endif
                                @endforeach
                            </tbody>
                        </table>
                        </div>
                        <div class="product-tab-list tab-pane fade" id="inactiveProduct">
                            <table id="myTable3" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Brand</th>
                                        <th>Status</th>
                                        <th>Purchases</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($products as $key => $product)
                                        @if ($product->status == "inactive")
                                        <tr>
                                            <td>
                                                {{--<img src="{!! asset('img/logo/logo.png') !!}" alt="">--}}
                                                {{ $product->name }}</td>
                                            <td>{{ $product->brand }}</td>
                                            <td>
                                                {{-- <button class="pd-setting">{{ $product->status }}</button> --}}
                                                {{ $product->status }}
                                            </td>
                                            <td>0</td>
                                            <td>
                                                <button data-toggle="tooltip" title="Detail" class="pd-setting-ed bg-pink"><a href="{{ route('product.edit', $product->id) }}"><i class="fa fa-file" aria-hidden="true"></i></a></button>
                                                {{-- <button data-toggle="tooltip" title="Seller" class="pd-setting-ed bg-cream"><a href="{{route('order.index')}}"><i class="fa fa-shopping-cart" aria-hidden="true"></i></a></button> --}}
                                                <button data-toggle="tooltip" title="Customer" class="pd-setting-ed bg-red"><a href="{{route('order.index')}}"><i class="fa fa-shopping-cart" aria-hidden="true"></i></a></button>
                                                <button data-toggle="tooltip" title="Asset" class="pd-setting-ed bg-green"><a href="{{ route('asset.show', $product->id) }}"><i class="fa fa-image" aria-hidden="true"></i></a></button>
                                                <button data-toggle="tooltip" title="Stock" class="pd-setting-ed bg-yellow"><a href="{{route('stock.index')}}"><i class="fa fa-archive" aria-hidden="true"></i></a></button>
                                                <button data-toggle="tooltip" title="Show" class="pd-setting-ed bg-orange"><a href="{{ route('product.show', $product->id) }}"><i class="fa fa-link" aria-hidden="true"></i></a></button>
                                                @if (Auth::user()->user_type != 'finance')
                                                  @if ($product->status == "active")
                                                    <button data-toggle="tooltip" title="Disable Product" class="btn btn-custon-rounded-three btn-danger"><a href="{{url('disable-product/'.$product->id)}}"><i class="fa fa-times adminpro-danger-error" aria-hidden="true"></i></a></button>
                                                  @else
                                                    <button data-toggle="tooltip" title="Enable Product" class="btn btn-custon-rounded-three btn-success"><a href="{{url('enable-product/'.$product->id)}}"><i class="fa fa-check adminpro-checked-pro" aria-hidden="true"></i></a></button>
                                                  @endif
                                                @endif
                                            </td>
                                        </tr>
                                        @endif
                                    @endforeach
                                </tbody>
                            </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script-extra')
    <script>
        $(document).ready( function () {
            $('#myTable,#myTable2,#myTable3').DataTable()
        } )
    </script>
@endsection